export const SET_TEMPLATE = "SET_TEMPLATE";
export const SET_PROJECT_TITLE = "SET_PROJECT_TITLE";
export const SET_NAVBAR_SECTION = "SET_NAVBAR_SECTION";
export const SET_MAIN_SECTION = "SET_MAIN_SECTION";
export const SET_ABOUT_SECTION = "SET_ABOUT_SECTION";
export const SET_SERVICE_SECTION = "SET_SERVICE_SECTION";
export const SET_CONTACT_SECTION = "SET_CONTACT_SECTION";
export const SET_FOOTER_SECTION = "SET_FOOTER_SECTION";
